name: CI

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositories 
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.ROLLOACCESSTOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Solve all
      run: dotnet run -c Release --no-build -- all
      working-directory: ./AdventOfCode
